import { Brand, ZtmStationWithPlatforms } from "../schema";

export const centrumStation: ZtmStationWithPlatforms = {
  name: "Centrum",
  normalizedName: "centrum",
  url: "https://www.wtp.waw.pl/rozklady-jazdy/?wtp_dt=2022-02-06&wtp_md=4&wtp_dy=7&wtp_st=7013",
  ztmId: "7013",
  platforms: [
    {
      direction: "Hoża",
      url: "https://www.wtp.waw.pl/rozklady-jazdy/?wtp_dt=2022-02-06&wtp_md=8&wtp_dy=7&wtp_st=7013&wtp_pt=01",
      isInSipTw: false,
      ztmStationId: "7013",
      number: "01",
      __brand: Brand.Platform,
    },
    {
      direction: "Al.Jerozolimskie",
      url: "https://www.wtp.waw.pl/rozklady-jazdy/?wtp_dt=2022-02-06&wtp_md=8&wtp_dy=7&wtp_st=7013&wtp_pt=03",
      isInSipTw: false,
      ztmStationId: "7013",
      number: "03",
      __brand: Brand.Platform,
    },
    {
      direction: "Metro Świętokrzyska",
      url: "https://www.wtp.waw.pl/rozklady-jazdy/?wtp_dt=2022-02-06&wtp_md=8&wtp_dy=7&wtp_st=7013&wtp_pt=04",
      isInSipTw: false,
      ztmStationId: "7013",
      number: "04",
      __brand: Brand.Platform,
    },
    {
      direction: "Krucza",
      url: "https://www.wtp.waw.pl/rozklady-jazdy/?wtp_dt=2022-02-06&wtp_md=8&wtp_dy=7&wtp_st=7013&wtp_pt=05",
      isInSipTw: false,
      ztmStationId: "7013",
      number: "05",
      __brand: Brand.Platform,
    },
    {
      direction: "Dw.Centralny",
      url: "https://www.wtp.waw.pl/rozklady-jazdy/?wtp_dt=2022-02-06&wtp_md=8&wtp_dy=7&wtp_st=7013&wtp_pt=06",
      isInSipTw: false,
      ztmStationId: "7013",
      number: "06",
      __brand: Brand.Platform,
    },
    {
      direction: "Hoża",
      url: "https://www.wtp.waw.pl/rozklady-jazdy/?wtp_dt=2022-02-06&wtp_md=8&wtp_dy=7&wtp_st=7013&wtp_pt=07",
      isInSipTw: true,
      ztmStationId: "7013",
      number: "07",
      __brand: Brand.Platform,
    },
    {
      direction: "Metro Świętokrzyska",
      url: "https://www.wtp.waw.pl/rozklady-jazdy/?wtp_dt=2022-02-06&wtp_md=8&wtp_dy=7&wtp_st=7013&wtp_pt=08",
      isInSipTw: true,
      ztmStationId: "7013",
      number: "08",
      __brand: Brand.Platform,
    },
    {
      direction: "Krucza",
      url: "https://www.wtp.waw.pl/rozklady-jazdy/?wtp_dt=2022-02-06&wtp_md=8&wtp_dy=7&wtp_st=7013&wtp_pt=09",
      isInSipTw: true,
      ztmStationId: "7013",
      number: "09",
      __brand: Brand.Platform,
    },
    {
      direction: "pl.Starynkiewicza",
      url: "https://www.wtp.waw.pl/rozklady-jazdy/?wtp_dt=2022-02-06&wtp_md=8&wtp_dy=7&wtp_st=7013&wtp_pt=10",
      isInSipTw: true,
      ztmStationId: "7013",
      number: "10",
      __brand: Brand.Platform,
    },
  ],
  __brand: Brand.StationWithPlatforms,
};

export const otherStationsWithCentrumInName: ZtmStationWithPlatforms[] = [
  {
    name: "Centrum Olimpijskie",
    normalizedName: "centrum olimpijskie",
    url: "https://www.wtp.waw.pl/rozklady-jazdy/?wtp_dt=2022-02-06&wtp_md=4&wtp_dy=7&wtp_st=6096",
    ztmId: "6096",
    platforms: [
      {
        direction: "most Gdański",
        url: "https://www.wtp.waw.pl/rozklady-jazdy/?wtp_dt=2022-02-06&wtp_md=8&wtp_dy=7&wtp_st=6096&wtp_pt=01",
        isInSipTw: false,
        ztmStationId: "6096",
        number: "01",
        __brand: Brand.Platform,
      },
      {
        direction: "Krasińskiego",
        url: "https://www.wtp.waw.pl/rozklady-jazdy/?wtp_dt=2022-02-06&wtp_md=8&wtp_dy=7&wtp_st=6096&wtp_pt=02",
        isInSipTw: false,
        ztmStationId: "6096",
        number: "02",
        __brand: Brand.Platform,
      },
    ],
    __brand: Brand.StationWithPlatforms,
  },
  {
    name: "Centrum Onkologii",
    normalizedName: "centrum onkologii",
    url: "https://www.wtp.waw.pl/rozklady-jazdy/?wtp_dt=2022-02-06&wtp_md=4&wtp_dy=7&wtp_st=3134",
    ztmId: "3134",
    platforms: [
      {
        direction: "Dereniowa",
        url: "https://www.wtp.waw.pl/rozklady-jazdy/?wtp_dt=2022-02-06&wtp_md=8&wtp_dy=7&wtp_st=3134&wtp_pt=01",
        isInSipTw: false,
        ztmStationId: "3134",
        number: "01",
        __brand: Brand.Platform,
      },
      {
        direction: "Łukaszczyka",
        url: "https://www.wtp.waw.pl/rozklady-jazdy/?wtp_dt=2022-02-06&wtp_md=8&wtp_dy=7&wtp_st=3134&wtp_pt=02",
        isInSipTw: false,
        ztmStationId: "3134",
        number: "02",
        __brand: Brand.Platform,
      },
      {
        direction: "Indiry Gandhi",
        url: "https://www.wtp.waw.pl/rozklady-jazdy/?wtp_dt=2022-02-06&wtp_md=8&wtp_dy=7&wtp_st=3134&wtp_pt=03",
        isInSipTw: false,
        ztmStationId: "3134",
        number: "03",
        __brand: Brand.Platform,
      },
      {
        direction: "Herbsta",
        url: "https://www.wtp.waw.pl/rozklady-jazdy/?wtp_dt=2022-02-06&wtp_md=8&wtp_dy=7&wtp_st=3134&wtp_pt=04",
        isInSipTw: false,
        ztmStationId: "3134",
        number: "04",
        __brand: Brand.Platform,
      },
    ],
    __brand: Brand.StationWithPlatforms,
  },
  {
    name: "Centrum Targowe",
    normalizedName: "centrum targowe",
    url: "https://www.wtp.waw.pl/rozklady-jazdy/?wtp_dt=2022-02-06&wtp_md=4&wtp_dy=7&wtp_st=3119",
    ztmId: "3119",
    platforms: [
      {
        direction: "Bokserska",
        url: "https://www.wtp.waw.pl/rozklady-jazdy/?wtp_dt=2022-02-06&wtp_md=8&wtp_dy=7&wtp_st=3119&wtp_pt=01",
        isInSipTw: false,
        ztmStationId: "3119",
        number: "01",
        __brand: Brand.Platform,
      },
      {
        direction: "rondo Żabczyńskiego",
        url: "https://www.wtp.waw.pl/rozklady-jazdy/?wtp_dt=2022-02-06&wtp_md=8&wtp_dy=7&wtp_st=3119&wtp_pt=02",
        isInSipTw: false,
        ztmStationId: "3119",
        number: "02",
        __brand: Brand.Platform,
      },
    ],
    __brand: Brand.StationWithPlatforms,
  },
  {
    name: "Centrum Zdrowia Dziecka",
    normalizedName: "centrum zdrowia dziecka",
    url: "https://www.wtp.waw.pl/rozklady-jazdy/?wtp_dt=2022-02-06&wtp_md=4&wtp_dy=7&wtp_st=2031",
    ztmId: "2031",
    platforms: [
      {
        direction: "Bielszowicka",
        url: "https://www.wtp.waw.pl/rozklady-jazdy/?wtp_dt=2022-02-06&wtp_md=8&wtp_dy=7&wtp_st=2031&wtp_pt=01",
        isInSipTw: false,
        ztmStationId: "2031",
        number: "01",
        __brand: Brand.Platform,
      },
      {
        direction: "Międzylesie",
        url: "https://www.wtp.waw.pl/rozklady-jazdy/?wtp_dt=2022-02-06&wtp_md=8&wtp_dy=7&wtp_st=2031&wtp_pt=02",
        isInSipTw: false,
        ztmStationId: "2031",
        number: "02",
        __brand: Brand.Platform,
      },
    ],
    __brand: Brand.StationWithPlatforms,
  },
  {
    name: "Metro Centrum Nauki Kopernik",
    normalizedName: "metro centrum nauki kopernik",
    url: "https://www.wtp.waw.pl/rozklady-jazdy/?wtp_dt=2022-02-06&wtp_md=4&wtp_dy=7&wtp_st=7079",
    ztmId: "7079",
    platforms: [
      {
        direction: "most Poniatowskiego",
        url: "https://www.wtp.waw.pl/rozklady-jazdy/?wtp_dt=2022-02-06&wtp_md=8&wtp_dy=7&wtp_st=7079&wtp_pt=01",
        isInSipTw: false,
        ztmStationId: "7079",
        number: "01",
        __brand: Brand.Platform,
      },
      {
        direction: "Karowa",
        url: "https://www.wtp.waw.pl/rozklady-jazdy/?wtp_dt=2022-02-06&wtp_md=8&wtp_dy=7&wtp_st=7079&wtp_pt=02",
        isInSipTw: false,
        ztmStationId: "7079",
        number: "02",
        __brand: Brand.Platform,
      },
      {
        direction: "most Świętokrzyski",
        url: "https://www.wtp.waw.pl/rozklady-jazdy/?wtp_dt=2022-02-06&wtp_md=8&wtp_dy=7&wtp_st=7079&wtp_pt=03",
        isInSipTw: false,
        ztmStationId: "7079",
        number: "03",
        __brand: Brand.Platform,
      },
      {
        direction: "Dobra",
        url: "https://www.wtp.waw.pl/rozklady-jazdy/?wtp_dt=2022-02-06&wtp_md=8&wtp_dy=7&wtp_st=7079&wtp_pt=04",
        isInSipTw: false,
        ztmStationId: "7079",
        number: "04",
        __brand: Brand.Platform,
      },
      {
        direction: "Wybrzeże Kościuszkowskie",
        url: "https://www.wtp.waw.pl/rozklady-jazdy/?wtp_dt=2022-02-06&wtp_md=8&wtp_dy=7&wtp_st=7079&wtp_pt=05",
        isInSipTw: false,
        ztmStationId: "7079",
        number: "05",
        __brand: Brand.Platform,
      },
    ],
    __brand: Brand.StationWithPlatforms,
  },
];
