export const TYPES = {
  ITimetableScrapeService: Symbol.for('ITimetableScrapeService'),
  IWebFetchService: Symbol.for('IWebFetchService'),
  IWebParseService: Symbol.for('IWebParseService'),
  IZtmParseService: Symbol.for('IZtmParseService'),
  IDbService: Symbol.for('IDbService'),
  DoController: Symbol.for('DoController'),
  GetController: Symbol.for('GetController'),
  MainController: Symbol.for('MainController'),
  IRealTimeDepartureService: Symbol.for('IRealTimeDepartureService'),
  IMatcherService: Symbol.for('IMatcherService'),
  IDepartureAggregator: Symbol.for('IDepartureAggregator'),
  IMessagePreparator: Symbol.for('IMessagePreparator'),
  IResponsePreparator: Symbol.for('IResponsePreparator'),
};
